[build]
  command = "npm install"
  functions = "netlify/functions"
  
[functions]
  node_bundler = "esbuild"
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  
[dev]
  command = "echo 'Netlify Functions development server'"
  port = 8888